steps:
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-f",
        "services/prospect-api/Dockerfile",
        "-t",
        "us-docker.pkg.dev/$PROJECT_ID/prospect-backend/api:${_IMAGE_TAG}",
        ".",
      ]
images:
  - "us-docker.pkg.dev/$PROJECT_ID/prospect-backend/api:${_IMAGE_TAG}"
